dds:
  robot_name: miranda
  namespace: advrf
  domain: 42
  declare_to_ros: true
  qos:
    reliability: reliable
    durability: transient_local
    history: keep_last
    depth: 1

joint_map:
  1: yaw_1
  2: pitch_1
  3: yaw_2
  4: pitch_2
  5: yaw_3
  6: pitch_3
  8: dagana